### ISSUE TITLE
オープンチャットルームnicknameない場合ipが同じになる

### ISSUE THREAD

**Issue by KuroiCc** [renasami/spring_training_2022#3]
オープンチャットルーム、headerにnicknameない場合は`f'unknown_{websocket.client.host}'`にしたが

dokcer内部にアクセスしているので正確のIPが取得できない、全部`unknown_172.18.0.1`になる

issuesとして記録しとく

**Comment by renasami** [comment]
フロントでvalidateしたから問題close
